Changes to be committed: 	modified:   INSTALL 	modified:   Makefile 	renamed:    README.txt -> README 	deleted:    err.log 	deleted:    examples/.README.txt.swp 	modified:   examples/README.html 	modified:   examples/README.txt 	new file:   genomedb/README 	renamed:    examples/genomes_chr_NC_gi.tar.gz -> genomedb/genomes_chr_NC_gi.tar.gz 	renamed:    examples/genomes_chr_hdr.tar.gz -> genomedb/genomes_chr_hdr.tar.gz 	new file:   genomedb/hg19/chr_NC_gi 	new file:   genomedb/hg19/chr_hdr 	new file:   genomedb/hg19/chrom1.seq.gz 	new file:   genomedb/hg19/chrom10.seq.gz 	new file:   genomedb/hg19/chrom11.seq.gz 	new file:   genomedb/hg19/chrom12.seq.gz 	new file:   genomedb/hg19/chrom13.seq.gz 	new file:   genomedb/hg19/chrom14.seq.gz 	new file:   genomedb/hg19/chrom15.seq.gz 	new file:   genomedb/hg19/chrom16.seq.gz 	new file:   genomedb/hg19/chrom17.seq.gz 	new file:   genomedb/hg19/chrom18.seq.gz 	new file:   genomedb/hg19/chrom19.seq.gz 	new file:   genomedb/hg19/chrom2.seq.gz 	new file:   genomedb/hg19/chrom20.seq.gz 	new file:   genomedb/hg19/chrom21.seq.gz 	new file:   genomedb/hg19/chrom22.seq.gz 	new file:   genomedb/hg19/chrom3.seq.gz 	new file:   genomedb/hg19/chrom4.seq.gz 	new file:   genomedb/hg19/chrom5.seq.gz 	new file:   genomedb/hg19/chrom6.seq.gz 	new file:   genomedb/hg19/chrom7.seq.gz 	new file:   genomedb/hg19/chrom8.seq.gz 	new file:   genomedb/hg19/chrom9.seq.gz 	new file:   genomedb/hg19/chromMt.seq.gz 	new file:   genomedb/hg19/chromX.seq.gz 	new file:   genomedb/hg19/chromY.seq.gz 	new file:   genomedb/hg19/normHeaders 	modified:   matrix_scan.c 	new file:   mscan2bed.o 	modified:   pwm_bowtie_wrapper 	modified:   pwm_convert 	modified:   pwm_mscan_wrapper 	modified:   pwm_scan 	new file:   pwmlib_scan 	new file:   pwmlibs/HOCOMOCOv11_HUMAN_matrix_logodds.mat 	new file:   pwmlibs/HOCOMOCOv11_HUMAN_matrix_probs.mat 	new file:   pwmlibs/HOCOMOCOv11_full_HUMAN_mono_meme_format.meme 	new file:   pwmlibs/HOCOMOCOv11_full_MOUSE_mono_meme_format.meme 	new file:   pwmlibs/JASPAR_CORE_2018_vert_matrix_logodds.mat 	new file:   pwmlibs/JASPAR_CORE_2018_vert_matrix_probs.mat 	new file:   pwmlibs/JASPAR_CORE_2018_vertebrates.meme 	new file:   pwmlibs/README 	deleted:    python/parallelize/parallelize.py~ 	modified:   python_tools/matrix_scan_parallel.py

diff --git a/pwm_bowtie_wrapper b/pwm_bowtie_wrapper
--- a/pwm_bowtie_wrapper
+++ b/pwm_bowtie_wrapper
@@ -1,29 +1,186 @@
 #!/bin/bash
 
-# pwm_bowtie_wrapper: scan a genome with a PWM (using bowtie)
+# pwm_bowtie_wrapper: scan a genome with a PWM (using Bowtie)
 #  arguments:
 #              matrix-file
 #              p-value
-#              bowtie-dir
-#              genome-idx-file
+#              genome-root-dir
 #              assembly
-#              non-overlapping matches [1/0]
+#
+#              forward scanning [-f]
+#              non-overlapping matches [DEFAULT]
+#              parallelize matrix_scan [-p]
+#              write output to file [-w]
 #
 #  25.11.2015  Giovanna Ambrosini
+#
+#  The <assembly> argument corresponds to the UCSC assembly name (e.g. hg19, mm9).
+#  The <genome-root-dir> is the root directory of the genome files.
+#
+#  The program writes the output to STDOUT, unless the -w option is specified, in which
+#  case results are written to file.
+#
+#  The <genome-root-dir> is the root directory of the genome files.
+#  The Bowtie index files are lacated in <genome-root-dir>/bowtie.
+#
+#  The variable chrNC_dir (used to define the location of the chr_NC_gi/chr_hdr files)
+#  is set to:
+#  chrNC_dir=<genome-root-dir>
+#
+#  The variable bin_dir is set to /home/local/bin
 #
 #  05.12.2017  Giovanna Ambrosini
 #              Optimize Bowtie pipeline
 #              Use new version of the mba program
-#
+#  12.12.2017  Giovanna Ambrosini
+#              Use getopts to parse script options
+#              Add forward scanning option
+#              Add write to file option
+#              Remove <genome-idx-file> argument
+#              (the variable is defined via the assoctaive array BOWTIEIDX)
+#  11.01.2018  Giovanna Ambrosini
+#              Simplify the definition of the path to the genome files:
+#              - the path to the assembly-specific data is defined by the
+#                <genome-root-dir> input argument
 
-ARGS=5         # Script requires 5 arguments.
 E_BADARGS=85   # Wrong number of arguments passed to script.
 
-if [ $# -lt "$ARGS" ]
+fwd_flag=""
+fwd_str=""
+forward=0
+w_flag=0
+non_overlapping=1
+parallel=0
+
+matrix_file=""
+p_value=""
+genome_root_dir=""
+genome_idx_file=""
+assembly=""
+
+display_usage() {
+      echo "Usage:"
+      echo "    pwm_bowtie_wrapper -m <matrix-file> -e <p-value> -d <genome-root-dir> -s <assembly[hg19|mm9|..]> [options]"
+      echo    "    - version 1.1.5"
+      echo    "    where options are:"
+      echo    "         -f  Scan sequences in forward direction [def=bidirectional]"
+      echo    "         -o  Allow for overlapping matches [def=non-overlapping matches]"
+      echo    "         -w  Write output to file [def=STDOUT]"
+      echo -e "         -p  Distribute matrix_scan on multiple CPU-cores [def=non-parallel processing]\n"
+      echo    "Please report bugs to Giovanna.Ambrosini@epfl.ch"
+}
+# Parse options
+while getopts ":hfopwm:e:d:s:" opt; do
+  case ${opt} in
+    h )
+      display_usage
+      exit 0
+      ;;
+    f )
+      forward=1
+      ;;
+    o )
+      non_overlapping=0
+      ;;
+    p )
+      parallel=1
+      ;;
+    m )
+      matrix_file=$OPTARG
+      ;;
+    e )
+      p_value=$OPTARG
+      ;;
+    d )
+      genome_root_dir=$OPTARG
+      ;;
+    s )
+      assembly=$OPTARG
+      ;;
+    w )
+      w_flag=1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+    \? )
+     echo "Invalid Option: -$OPTARG" 1>&2
+     exit 1
+     ;;
+  esac
+done
+shift $((OPTIND -1))
+
+parsed_args=$((OPTIND -1))
+
+if [ $parsed_args -le 1 ]
 then
-  echo "Usage: `basename $0` <matrix-file> <p-value> <bowtie-dir> <genome-idx-file> <assembly[hg19|mm9|..]> [<non-overlapping matches [1/0]>]"
-  exit $E_BADARGS
+  display_usage
+  exit 1
 fi
+
+#echo "Matrix file    : $matrix_file" >&2
+#echo "P-value        : $p_value" >&2
+#echo "genome_root_dir: $genome_root_dir" >&2
+#echo "assembly       : $assembly" >&2
+
+if [ -z "$matrix_file" ]
+then
+  echo "Please specify the PWM file (-m)" >&2
+  exit 1
+fi
+if [ -z "$p_value" ]
+then
+  echo "Please specify the p-value (-e)" >&2
+  exit 1
+fi
+if [ -z "$genome_root_dir" ]
+then
+  echo "Please specify the genome root directory (-d)" >&2
+  exit 1
+fi
+if [ -z "$assembly" ]
+then
+  echo "Please specify the species assembly (-s)" >&2
+  exit 1
+fi
+
+bin_dir=$(echo /home/local/bin)
+
+bowtie_dir=$genome_root_dir"/bowtie"
+
+# Define the path to the assembly tables chr_NC_gi/chr_hdr (needed for BED-format conversion)
+chrNC_dir=$genome_root_dir
+
+# Declare associative array for bowtie index files
+declare -A BOWTIEIDX
+BOWTIEIDX[hg19]=h_sapiens_hg19
+BOWTIEIDX[hg18]=h_sapiens_hg18
+BOWTIEIDX[hg38]=h_sapiens_hg38
+BOWTIEIDX[mm9]=m_musculus_mm9
+BOWTIEIDX[mm10]=m_musculus_mm10
+BOWTIEIDX[bosTau3]=b_taurus_bosTau3
+BOWTIEIDX[bosTau8]=b_taurus_bosTau8
+BOWTIEIDX[canFam2]=c_familiaris_canFam2
+BOWTIEIDX[canFam3]=c_familiaris_canFam3
+BOWTIEIDX[panTro2]=p_troglodytes_panTro2
+BOWTIEIDX[panTro5]=p_troglodytes_panTro5
+BOWTIEIDX[rn5]=r_norvegicus_rn5
+BOWTIEIDX[rn6]=r_norvegicus_rn6
+BOWTIEIDX[dm3]=d_melanogaster_dm3
+BOWTIEIDX[dm6]=d_melanogaster_dm6
+BOWTIEIDX[ce6]=c_elegans_ce6
+BOWTIEIDX[ce10]=c_elegans_ce10
+BOWTIEIDX[ce11]=c_elegans_ce11
+BOWTIEIDX[danRer5]=d_rerio_danRer5
+BOWTIEIDX[danRer7]=d_rerio_danRer7
+BOWTIEIDX[danRer10]=d_rerio_danRer10
+BOWTIEIDX[sacCer2]=s_cerevisiae_sacCer2
+BOWTIEIDX[sacCer3]=s_cerevisiae_sacCer3
+
+#echo ${BOWTIEIDX[$assembly]} 
+genome_idx_file=${BOWTIEIDX[$assembly]}
 
 # Declare associative array for background base composition
 declare -A BGFREQ
@@ -51,92 +208,96 @@ BGFREQ[danRer10]=0.32,0.18,0.18,0.32
 BGFREQ[sacCer2]=0.31,0.19,0.19,0.31
 BGFREQ[sacCer3]=0.31,0.19,0.19,0.31
 
-echo "BG nucleotide composition: ${BGFREQ[$5]}"
-bg_freq=${BGFREQ[$5]}
+echo "BG nucleotide composition: ${BGFREQ[$assembly]}" >&2
+bg_freq=${BGFREQ[$assembly]}
 
-chrNC_dir=/home/local/db/genome
-
-non_overlapping=1
 
 if [ $# == 6 ]
 then
   non_overlapping=$6
 fi
 
-if [ -f "$1" ]
+if [ ! -f "$matrix_file" ]
 then
-    matrix_file=$1
-else
-    echo "File \"$1\" does not exist."
-    exit $E_BADARGS
+  echo "Matrix File \"$1\" does not exist." >&2
+  exit $E_BADARGS
 fi
 
-p_value=$2
-bowtie_dir=$3
-
-if [ -f "$3/$4.1.ebwt" ]
+if [ ! -f "$bowtie_dir/$genome_idx_file.1.ebwt" ]
 then
-    genome_idx_file=$4
-else
-    echo "File \"$3/$4.1.ebwt\" does not exist."
-    exit $E_BADARGS
+  echo "Genome File \"$1\" does not exist." >&2
+  exit $E_BADARGS
 fi
-
-assembly=$5
 
 # Extract basename from matrix file (without path)
 matrix_name=$(basename "$matrix_file")
 extension="${matrix_name##*.}"
 matrix_name="${matrix_name%.*}"
+matrix_name=${matrix_name%.mat}
 
-echo "PWM name: $matrix_name"
+echo "PWM name: $matrix_name" >&2
 
-echo "========               Computing PWM length                ========"
+echo "========               Computing PWM length                ========" >&2
 matrix_len=$(cat $matrix_file | perl -ane 'next if (/^#/ or /^>/); print;' | wc -l)
 
 file_len=$(cat $matrix_file | wc -l)
 
-echo "PWM file: $matrix_file"
-echo "PWM length: $matrix_len"
-echo "PWM file length : $file_len lines"
+echo "PWM file: $matrix_file" >&2
+echo "PWM length: $matrix_len" >&2
+echo "PWM file length : $file_len lines" >&2
 
-echo "========               Calculating PWM score               ========"
+echo "========               Calculating PWM score               ========" >&2
 matrix_score=$(matrix_prob -e $p_value --bg "$bg_freq" $matrix_file \
 	| grep SCORE | sed 's/:/\ /'\
 	| awk -F " " '{print $2}')
 
-echo "PWM score: $matrix_score"
+echo "PWM score: $matrix_score" >&2
+
+if [ $forward == 1 ]
+then
+  echo "Scanning in forward direction..." >&2
+  fwd_str="fwd_"
+  fwd_flag="--norc"
+fi
 
 if [ $non_overlapping == 1 ]
 then
-  echo "Output non-overlapping matches..."
+  echo "Output non-overlapping matches..." >&2
 fi
 
-echo "========               Generating PWM score distribution   ========"
+echo "========               Generating PWM score distribution   ========" >&2
 # Generate the Matrix Score Cumulative Table
 pwmScore_tab=${matrix_name}_co${matrix_score}_scoretab.txt
 matrix_prob --bg "$bg_freq" $matrix_file 2>/dev/null > $pwmScore_tab
 
-echo "PWM distribution score: $pwmScore_tab"
+echo "PWM distribution score: $pwmScore_tab" >&2
 
 # Run the Bowtie pipeline
-pwmout_bed=${matrix_name}_co${matrix_score}_bowtie.bed
-
-echo "========               Bowtie-based pipeline               ========"
-if [ $non_overlapping == 0 ]
+if [ $w_flag == 1 ]
 then
-  echo "mba -c $matrix_score $matrix_file | awk '{print \">\"\$2\"\n\"\$1}' | bowtie --threads 4 -l $matrix_len -n0 -a $bowtie_dir/$genome_idx_file -f - --un unmapped.dat | sort -s -k3,3 -k4,4n | bowtie2bed -s $assembly -l $matrix_len -i $chrNC_dir | awk 'BEGIN { while((getline line < \"$pwmScore_tab\") > 0 ) {split(line,f,\" \"); pvalue[f[1]]=f[2]} close(\"$pwmScore_tab\")} {print \$1\"\t\"\$2\"\t\"\$3\"\t\"\$4\"\t\"\$5\"\t\"\$6\"\t\"\"$matrix_name\"\"\t\"\"P-value=\"pvalue[\$5]}' > $pwmout_bed" 
-  echo "..."
-  mba -c $matrix_score $matrix_file | awk '{print ">"$2"\n"$1}' | bowtie --threads 4 -l $matrix_len -n0 -a $bowtie_dir/$genome_idx_file -f - --un unmapped.dat | sort -s -k3,3 -k4,4n | bowtie2bed -s $assembly -l $matrix_len -i $chrNC_dir | awk -v scoretab="$pwmScore_tab" -v pwmname="$matrix_name" 'BEGIN { while((getline line < scoretab) > 0 ) {split(line,f," "); pvalue[f[1]]=f[2]} close(scoretab)} {print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"pwmname"\t""P-value="pvalue[$5]}' > $pwmout_bed
+  pwmout_bed=${matrix_name}_co${matrix_score}_${fwd_str}bowtie.bed
 else
-  echo "mba -c $matrix_score $matrix_file | awk '{print \">\"\$2\"\n\"\$1}' | bowtie --threads 4 -l $matrix_len -n0 -a $bowtie_dir/$genome_idx_file -f - --un unmapped.dat | sort -s -k3,3 -k4,4n | bowtie2bed -s $assembly -l $matrix_len -i $chrNC_dir | filterOverlaps -l$matrix_len  | awk 'BEGIN { while((getline line < \"$pwmScore_tab\") > 0 ) {split(line,f,\" \"); pvalue[f[1]]=f[2]} close(\"$pwmScore_tab\")} {print \$1\"\t\"\$2\"\t\"\$3\"\t\"\$4\"\t\"\$5\"\t\"\$6\"\t\"\"$matrix_name\"\"\t\"\"P-value=\"pvalue[\$5]}' > $pwmout_bed" 
-  echo "..."
-  mba -c $matrix_score $matrix_file | awk '{print ">"$2"\n"$1}' | bowtie --threads 4 -l $matrix_len -n0 -a $bowtie_dir/$genome_idx_file -f - --un unmapped.dat | sort -s -k3,3 -k4,4n | bowtie2bed -s $assembly -l $matrix_len -i $chrNC_dir | filterOverlaps -l$matrix_len | awk -v scoretab="$pwmScore_tab" -v pwmname="$matrix_name" 'BEGIN { while((getline line < scoretab) > 0 ) {split(line,f," "); pvalue[f[1]]=f[2]} close(scoretab)} {print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"pwmname"\t""P-value="pvalue[$5]}' > $pwmout_bed
+  pwmout_bed="/dev/stdout"
 fi
 
-echo "List of matches (BED format) : $pwmout_bed"
-nb_hits=`cat $pwmout_bed|wc -l`
-echo "Total number of PWM matches  : $nb_hits"
+echo "========               Bowtie-based pipeline               ========" >&2
+if [ $non_overlapping == 0 ]
+then
+  echo "$bin_dir/mba -c $matrix_score $matrix_file | awk '{print \">\"\$2\"\n\"\$1}' | $bin_dir/bowtie --threads 4 $fwd_flag -l $matrix_len -n0 -a $bowtie_dir/$genome_idx_file -f - --un unmapped.dat | sort -s -k3,3 -k4,4n | $bin_dir/bowtie2bed -s $assembly -l $matrix_len -i $chrNC_dir | awk 'BEGIN { while((getline line < \"$pwmScore_tab\") > 0 ) {split(line,f,\" \"); pvalue[f[1]]=f[2]} close(\"$pwmScore_tab\")} {print \$1\"\t\"\$2\"\t\"\$3\"\t\"\$4\"\t\"\$5\"\t\"\$6\"\t\"\"$matrix_name\"\"\t\"\"P-value=\"pvalue[\$5]}' >$pwmout_bed" >&2
+  echo "..." >&2
+  $bin_dir/mba -c $matrix_score $matrix_file | awk '{print ">"$2"\n"$1}' | $bin_dir/bowtie --threads 4 $fwd_flag -l $matrix_len -n0 -a $bowtie_dir/$genome_idx_file -f - --un unmapped.dat | sort -s -k3,3 -k4,4n | $bin_dir/bowtie2bed -s $assembly -l $matrix_len -i $chrNC_dir | awk -v scoretab="$pwmScore_tab" -v pwmname="$matrix_name" 'BEGIN { while((getline line < scoretab) > 0 ) {split(line,f," "); pvalue[f[1]]=f[2]} close(scoretab)} {print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"pwmname"\t""P-value="pvalue[$5]}' >$pwmout_bed
+else
+  echo "$bin_dir/mba -c $matrix_score $matrix_file | awk '{print \">\"\$2\"\n\"\$1}' | $bin_dir/bowtie --threads 4 $fwd_flag -l $matrix_len -n0 -a $bowtie_dir/$genome_idx_file -f - --un unmapped.dat | sort -s -k3,3 -k4,4n | $bin_dir/bowtie2bed -s $assembly -l $matrix_len -i $chrNC_dir | filterOverlaps -l$matrix_len  | awk 'BEGIN { while((getline line < \"$pwmScore_tab\") > 0 ) {split(line,f,\" \"); pvalue[f[1]]=f[2]} close(\"$pwmScore_tab\")} {print \$1\"\t\"\$2\"\t\"\$3\"\t\"\$4\"\t\"\$5\"\t\"\$6\"\t\"\"$matrix_name\"\"\t\"\"P-value=\"pvalue[\$5]}' >$pwmout_bed" >&2
+  echo "..." >&2
+  $bin_dir/mba -c $matrix_score $matrix_file | awk '{print ">"$2"\n"$1}' | $bin_dir/bowtie --threads 4 $fwd_flag -l $matrix_len -n0 -a $bowtie_dir/$genome_idx_file -f - --un unmapped.dat | sort -s -k3,3 -k4,4n | $bin_dir/bowtie2bed -s $assembly -l $matrix_len -i $chrNC_dir | filterOverlaps -l$matrix_len | awk -v scoretab="$pwmScore_tab" -v pwmname="$matrix_name" 'BEGIN { while((getline line < scoretab) > 0 ) {split(line,f," "); pvalue[f[1]]=f[2]} close(scoretab)} {print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"pwmname"\t""P-value="pvalue[$5]}' >$pwmout_bed
+fi
+
+if [ $w_flag == 1 ]
+then
+  echo "List of matches (BED format) : $pwmout_bed" >&2
+  nb_hits=`cat $pwmout_bed|wc -l`
+  echo "Total number of PWM matches  : $nb_hits" >&2
+fi
 
 if [ -e unmapped.dat ]
 then
diff --git a/pwm_mscan_wrapper b/pwm_mscan_wrapper
--- a/pwm_mscan_wrapper
+++ b/pwm_mscan_wrapper
@@ -4,27 +4,155 @@
 #  arguments:
 #              matrix-file
 #              p-value
-#              genome-dir
+#              genome-root-dir
 #              assembly
-#              non-overlapping matches [1/0]
-#              parallel processing [1/0]
+#
+#              forward scanning [-f]
+#              non-overlapping matches [DEFAULT]
+#              parallel processing [-p]
+#              write output to file [-w]
 #
 #  25.11.2015  Giovanna Ambrosini
 #
-#  05.12.2017  Giovanna Ambrosini
-#              Use new faster version of the matrix_scan program
+#  The <assembly> argument corresponds to the UCSC assembly name (e.g. hg19, mm9).
 #
+#  If specified (via the -p option), matrix_scan can be run in parallel.
+#  This is only possible on a multi-core processor architecture.
+#
+#  The <genome-root-dir> is the root directory of the genome files (i.e. the FASTA
+#  chromosome files used by matrix_scan).
+#
+#  The variable chrNC_dir (used to define the location of the chr_NC_gi/chr_hdr files)
+#  is set to:
+#  chrNC_dir=<genome-root-dir>
+#
+#  The variable bin_dir is set to /home/local/bin
+#
+#  The program writes the output to STDOUT, unless the -w option is specified, in which
+#  case results are written to file.
+#
+#  05.12.2017  Giovanna Ambrosini
+#              Use the new faster version of the matrix_scan program
+#  07.12.2017  Giovanna Ambrosini
+#              Use getopts to parse script options
+#              Add forward scanning option
+#  12.12.2017  Giovanna Ambrosini
+#              Use getopts to parse script options
+#              Add forward scanning option
+#              Add write to file option
+#  11.01.2018  Giovanna Ambrosini
+#              Simplify the definition of the path to the genome files:
+#              - the path to the assembly-specific data is defined by the
+#                <genome-root-dir> input argument
 
-ARGS=4         # Script takes 6 arguments, but at least 4 arguments are mandatory.
 E_BADARGS=85   # Wrong number of arguments passed to script.
 
-if [ $# -lt "$ARGS" ]
+fwd_flag=""
+fwd_str=""
+forward=0
+w_flag=0
+non_overlapping=1
+parallel=0
+
+matrix_file=""
+p_value=""
+genome_root_dir=""
+assembly=""
+
+display_usage() {
+      echo "Usage:"
+      echo    "    pwm_mscan_wrapper -m <matrix-file> -e <p-value> -d <genome-root-dir> -s <assembly[hg19|mm9|..]> [options]"
+      echo    "    - version 1.1.5"
+      echo    "    where options are:"
+      echo    "         -f  Scan sequences in forward direction [def=bidirectional]"
+      echo    "         -o  Allow for overlapping matches [def=non-overlapping matches]"
+      echo    "         -w  Write output to file [def=STDOUT]"
+      echo -e "         -p  Distribute matrix_scan on multiple cores [def=non-parallel processing]\n"
+      echo "Please report bugs to Giovanna.Ambrosini@epfl.ch"
+}
+# Parse options
+while getopts ":hfopwm:e:d:s:" opt; do
+  case ${opt} in
+    h )
+      display_usage
+      exit 0
+      ;;
+    f )
+      forward=1
+      ;;
+    o )
+      non_overlapping=0
+      ;;
+    p )
+      parallel=1
+      ;;
+    m )
+      matrix_file=$OPTARG
+      ;;
+    e )
+      p_value=$OPTARG
+      ;;
+    d )
+      genome_root_dir=$OPTARG
+      ;;
+    s )
+      assembly=$OPTARG
+      ;;
+    w )
+      w_flag=1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+    \? )
+     echo "Invalid Option: -$OPTARG" 1>&2
+     exit 1
+     ;;
+  esac
+done
+shift $((OPTIND -1))
+
+parsed_args=$((OPTIND -1))
+
+if [ $parsed_args -le 1 ]
 then
-  echo "Usage: `basename $0` <matrix-file> <p-value> <genome-dir> <assembly[hg19|mm9|..]> [<non-overlapping matches [1/0]>] [<parallel [1/0]>]"
-  exit $E_BADARGS
+  display_usage
+  exit 1
+fi
+
+#echo "Matrix file    : $matrix_file" >&2
+#echo "P-value        : $p_value" >&2
+#echo "genome-root-dir: $genome_root_dir" >&2
+#echo "assembly       : $assembly" >&2
+#echo "Write flag     : $w_flag" >&2
+
+if [ -z "$matrix_file" ]
+then 
+  echo "Please specify the PWM file (-m)" >&2
+  exit 1
+fi
+if [ -z "$p_value" ]
+then 
+  echo "Please specify the p-value (-e)" >&2
+  exit 1
+fi
+if [ -z "$genome_root_dir" ]
+then 
+  echo "Please specify the genome root directory (-d)" >&2
+  exit 1
+fi
+if [ -z "$assembly" ]
+then 
+  echo "Please specify the species assembly (-s)" >&2
+  exit 1
 fi
 
 bin_dir=$(echo /home/local/bin)
+assembly_dir=$genome_root_dir"/"$assembly
+
+# Define path for files chr_NC_gi/chr_hdr (needed for BED-format conversion)
+chrNC_dir=$genome_root_dir
 
 # Declare associative array for background base composition
 declare -A BGFREQ
@@ -52,56 +180,33 @@ BGFREQ[danRer10]=0.32,0.18,0.18,0.32
 BGFREQ[sacCer2]=0.31,0.19,0.19,0.31
 BGFREQ[sacCer3]=0.31,0.19,0.19,0.31
 
-echo "BG nucleotide composition: ${BGFREQ[$4]}"
-bg_freq=${BGFREQ[$4]}
+echo "BG nucleotide composition: ${BGFREQ[$assembly]}" >&2
+bg_freq=${BGFREQ[$assembly]}
 
 widx_size=""
 
-non_overlapping=1
-
-if [ $# -ge 5 ]
+if [ ! -f "$matrix_file" ]
 then
-  non_overlapping=$5
+  echo "Matrix File \"$1\" does not exist."
+  exit $E_BADARGS
 fi
-
-parallel=1
-
-if [ $# == 6 ]
-then
-  parallel=$6
-fi
-
-if [ -f "$1" ]
-then
-    matrix_file=$1
-else
-    echo "File \"$1\" does not exist."
-    exit $E_BADARGS
-fi
-
-p_value=$2
-genome_dir=$3
-
-# Define path for files chr_NC_gi/chr_hdr (needed for BED-format conversion)
-chrNC_dir=$genome_dir
-
-assembly=$4
 
 # Extract basename from matrix file (without path)
 matrix_name=$(basename "$matrix_file")
 extension="${matrix_name##*.}"
 matrix_name="${matrix_name%.*}"
+matrix_name=${matrix_name%.mat}
 
-echo "PWM name: $matrix_name"
+echo "PWM name: $matrix_name" >&2
 
-echo "========               Computing PWM length                ========"
+echo "========               Computing PWM length                ========" >&2
 matrix_len=$(cat $matrix_file | perl -ane 'next if (/^#/ or /^>/); print;' | wc -l)
 
 file_len=$(cat $matrix_file | wc -l)
 
-echo "PWM file: $matrix_file"
-echo "PWM length: $matrix_len"
-echo "PWM file length : $file_len"
+echo "PWM file: $matrix_file" >&2
+echo "PWM length: $matrix_len" >&2
+echo "PWM file length : $file_len" >&2
 
 if [ "$matrix_len" -gt "17" ]
 then
@@ -112,64 +217,78 @@ then
   fi
 fi
 
-echo "========               Calculating PWM score               ========"
+echo "========               Calculating PWM score               ========" >&2
 matrix_score=$(matrix_prob -e $p_value --bg "$bg_freq" $matrix_file \
         | grep SCORE | sed 's/:/\ /'\
         | awk -F " " '{print $2}')
 
-echo "PWM score: $matrix_score"
-#echo "parallelize: $parallel"
+echo "PWM score: $matrix_score" >&2
 
 # Run matrix_scan pipeline
 
+if [ $forward == 1 ]
+then
+  echo "Scanning in forward direction..." >&2
+  fwd_flag="-f"
+  fwd_str="fwd_"
+fi
+
 if [ $parallel == 1 ]
 then
-  echo "Parallelize matrix_scan..."
+  echo "Parallelize matrix_scan..." >&2
 fi
 
 if [ $non_overlapping == 1 ]
 then
-  echo "Output non-overlapping matches..."
+  echo "Output non-overlapping matches..." >&2
 fi
 
-echo "========               Generating PWM score distribution   ========"
+echo "========               Generating PWM score distribution   ========" >&2
 # Generate the Matrix Score Cumulative Table
 pwmScore_tab=${matrix_name}_co${matrix_score}_scoretab.txt
 matrix_prob --bg "$bg_freq" $matrix_file 2>/dev/null > $pwmScore_tab
 
-echo "PWM distribution score: $pwmScore_tab"
+echo "PWM distribution score: $pwmScore_tab" >&2
 
 # Run the matrix_scan pipeline
-pwmout_bed=${matrix_name}_co${matrix_score}_matrix_scan.bed
+if [ $w_flag == 1 ]
+then
+  pwmout_bed=${matrix_name}_co${matrix_score}_${fwd_str}matrix_scan.bed
+else
+  pwmout_bed="/dev/stdout"
+fi
 
-echo "========               matrix_scan-based pipeline          ========"
+echo "========               matrix_scan-based pipeline          ========" >&2
 if [ $parallel == 0 ]
 then
   if [ $non_overlapping == 0 ]
   then
-    echo "cat $genome_dir/$assembly/chrom[^M]*.seq | $bin_dir/matrix_scan -m $matrix_file -c $matrix_score $widx_size | sort -s -k1,1 -k2,2n | mscan2bed -s $assembly -i $chrNC_dir | awk 'BEGIN { while((getline line < \"$pwmScore_tab\") > 0 ) {split(line,f,\" \"); pvalue[f[1]]=f[2]} close(\"$pwmScore_tab\")} {print \$1\"\t\"\$2\"\t\"\$3\"\t\"\$4\"\t\"\$5\"\t\"\$6\"\t\"\"$matrix_name\"\"\t\"\"P-value=\"pvalue[\$5]}' > $pwmout_bed" 
-    echo "..."
-    cat $genome_dir/$assembly/chrom[^M]*.seq | $bin_dir/matrix_scan -m $matrix_file -c $matrix_score $widx_size | sort -s -k1,1 -k2,2n | mscan2bed -s $assembly -i $chrNC_dir | awk -v scoretab="$pwmScore_tab" -v pwmname="$matrix_name" 'BEGIN { while((getline line < scoretab) > 0 ) {split(line,f," "); pvalue[f[1]]=f[2]} close(scoretab)} {print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"pwmname"\t""P-value="pvalue[$5]}' > $pwmout_bed
+    echo "cat $assembly_dir/chrom[^M]*.seq | $bin_dir/matrix_scan -m $matrix_file -c $matrix_score $fwd_flag $widx_size | sort -s -k1,1 -k2,2n | $bin_dir/mscan2bed -s $assembly -i $chrNC_dir | awk 'BEGIN { while((getline line < \"$pwmScore_tab\") > 0 ) {split(line,f,\" \"); pvalue[f[1]]=f[2]} close(\"$pwmScore_tab\")} {print \$1\"\t\"\$2\"\t\"\$3\"\t\"\$4\"\t\"\$5\"\t\"\$6\"\t\"\"$matrix_name\"\"\t\"\"P-value=\"pvalue[\$5]}' >$pwmout_bed" >&2
+    echo "..." >&2
+    cat $assembly_dir/chrom[^M]*.seq | $bin_dir/matrix_scan -m $matrix_file -c $matrix_score $fwd_flag $widx_size | sort -s -k1,1 -k2,2n | $bin_dir/mscan2bed -s $assembly -i $chrNC_dir | awk -v scoretab="$pwmScore_tab" -v pwmname="$matrix_name" 'BEGIN { while((getline line < scoretab) > 0 ) {split(line,f," "); pvalue[f[1]]=f[2]} close(scoretab)} {print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"pwmname"\t""P-value="pvalue[$5]}' >$pwmout_bed
   else
-    echo "cat $genome_dir/$assembly/chrom[^M]*.seq | $bin_dir/matrix_scan -m $matrix_file -c $matrix_score $widx_size | sort -s -k1,1 -k2,2n | mscan2bed -s $assembly -i $chrNC_dir | filterOverlaps -l$matrix_len | awk 'BEGIN { while((getline line < \"$pwmScore_tab\") > 0 ) {split(line,f,\" \"); pvalue[f[1]]=f[2]} close(\"$pwmScore_tab\")} {print \$1\"\t\"\$2\"\t\"\$3\"\t\"\$4\"\t\"\$5\"\t\"\$6\"\t\"\"$matrix_name\"\"\t\"\"P-value=\"pvalue[\$5]}' > $pwmout_bed" 
-    echo "..."
-    cat $genome_dir/$assembly/chrom[^M]*.seq | $bin_dir/matrix_scan -m $matrix_file -c $matrix_score $widx_size | sort -s -k1,1 -k2,2n | mscan2bed -s $assembly -i $chrNC_dir | filterOverlaps -l$matrix_len | awk -v scoretab="$pwmScore_tab" -v pwmname="$matrix_name" 'BEGIN { while((getline line < scoretab) > 0 ) {split(line,f," "); pvalue[f[1]]=f[2]} close(scoretab)} {print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"pwmname"\t""P-value="pvalue[$5]}' > $pwmout_bed
+    echo "cat $assembly_dir/chrom[^M]*.seq | $bin_dir/matrix_scan -m $matrix_file -c $matrix_score $fwd_flag $widx_size | sort -s -k1,1 -k2,2n | $bin_dir/mscan2bed -s $assembly -i $chrNC_dir | filterOverlaps -l$matrix_len | awk 'BEGIN { while((getline line < \"$pwmScore_tab\") > 0 ) {split(line,f,\" \"); pvalue[f[1]]=f[2]} close(\"$pwmScore_tab\")} {print \$1\"\t\"\$2\"\t\"\$3\"\t\"\$4\"\t\"\$5\"\t\"\$6\"\t\"\"$matrix_name\"\"\t\"\"P-value=\"pvalue[\$5]}' >$pwmout_bed" >&2
+    echo "..." >&2
+    cat $assembly_dir/chrom[^M]*.seq | $bin_dir/matrix_scan -m $matrix_file -c $matrix_score $fwd_flag $widx_size | sort -s -k1,1 -k2,2n | $bin_dir/mscan2bed -s $assembly -i $chrNC_dir | filterOverlaps -l$matrix_len | awk -v scoretab="$pwmScore_tab" -v pwmname="$matrix_name" 'BEGIN { while((getline line < scoretab) > 0 ) {split(line,f," "); pvalue[f[1]]=f[2]} close(scoretab)} {print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"pwmname"\t""P-value="pvalue[$5]}' >$pwmout_bed
   fi
 else
   if [ $non_overlapping == 0 ]
   then
-    echo "python $bin_dir/matrix_scan_parallel.py -m $matrix_file -f \"\$(ls $genome_dir/$assembly/chrom*.seq|grep -v chromMt)\" -c $matrix_score $widx_size -p 15 | sort -s -k1,1 -k2,2n | mscan2bed -s $assembly -i $chrNC_dir | awk 'BEGIN { while((getline line < \"$pwmScore_tab\") > 0 ) {split(line,f,\" \"); pvalue[f[1]]=f[2]} close(\"$pwmScore_tab\")} {print \$1\"\t\"\$2\"\t\"\$3\"\t\"\$4\"\t\"\$5\"\t\"\$6\"\t\"\"$matrix_name\"\"\t\"\"P-value=\"pvalue[\$5]}' > $pwmout_bed" 
-    echo "..."
-    python $bin_dir/matrix_scan_parallel.py -m $matrix_file -f "$(ls $genome_dir/$assembly/chrom*.seq|grep -v chromMt)" -c $matrix_score $widx_size -p 15 | sort -s -k1,1 -k2,2n | mscan2bed -s $assembly -i $chrNC_dir | awk -v scoretab="$pwmScore_tab" -v pwmname="$matrix_name" 'BEGIN { while((getline line < scoretab) > 0 ) {split(line,f," "); pvalue[f[1]]=f[2]} close(scoretab)} {print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"pwmname"\t""P-value="pvalue[$5]}' > $pwmout_bed
+    echo "python $bin_dir/matrix_scan_parallel.py -m $matrix_file -s \"\$(ls $assembly_dir/chrom*.seq|grep -v chromMt)\" -c $matrix_score $fwd_flag $widx_size -p 15 | sort -s -k1,1 -k2,2n | $bin_dir/mscan2bed -s $assembly -i $chrNC_dir | awk 'BEGIN { while((getline line < \"$pwmScore_tab\") > 0 ) {split(line,f,\" \"); pvalue[f[1]]=f[2]} close(\"$pwmScore_tab\")} {print \$1\"\t\"\$2\"\t\"\$3\"\t\"\$4\"\t\"\$5\"\t\"\$6\"\t\"\"$matrix_name\"\"\t\"\"P-value=\"pvalue[\$5]}' >$pwmout_bed" >&2
+    echo "..." >&2
+    python $bin_dir/matrix_scan_parallel.py -m $matrix_file -s "$(ls $assembly_dir/chrom*.seq|grep -v chromMt)" -c $matrix_score $fwd_flag $widx_size -p 15 | sort -s -k1,1 -k2,2n | $bin_dir/mscan2bed -s $assembly -i $chrNC_dir | awk -v scoretab="$pwmScore_tab" -v pwmname="$matrix_name" 'BEGIN { while((getline line < scoretab) > 0 ) {split(line,f," "); pvalue[f[1]]=f[2]} close(scoretab)} {print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"pwmname"\t""P-value="pvalue[$5]}' >$pwmout_bed
   else
-    echo "python $bin_dir/matrix_scan_parallel.py -m $matrix_file -f \"\$(ls $genome_dir/$assembly/chrom*.seq|grep -v chromMt)\" -c $matrix_score $widx_size -p 15 | sort -s -k1,1 -k2,2n | mscan2bed -s $assembly -i $chrNC_dir | filterOverlaps -l$matrix_len | awk 'BEGIN { while((getline line < \"$pwmScore_tab\") > 0 ) {split(line,f,\" \"); pvalue[f[1]]=f[2]} close(\"$pwmScore_tab\")} {print \$1\"\t\"\$2\"\t\"\$3\"\t\"\$4\"\t\"\$5\"\t\"\$6\"\t\"\"$matrix_name\"\"\t\"\"P-value=\"pvalue[\$5]}' > $pwmout_bed" 
-    echo "..."
-    python $bin_dir/matrix_scan_parallel.py -m $matrix_file -f "$(ls $genome_dir/$assembly/chrom*.seq|grep -v chromMt)" -c $matrix_score $widx_size -p 15 | sort -s -k1,1 -k2,2n | mscan2bed -s $assembly -i $chrNC_dir | filterOverlaps -l$matrix_len | awk -v scoretab="$pwmScore_tab" -v pwmname="$matrix_name" 'BEGIN { while((getline line < scoretab) > 0 ) {split(line,f," "); pvalue[f[1]]=f[2]} close(scoretab)} {print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"pwmname"\t""P-value="pvalue[$5]}' > $pwmout_bed
+    echo "python $bin_dir/matrix_scan_parallel.py -m $matrix_file -s \"\$(ls $assembly_dir/chrom*.seq|grep -v chromMt)\" -c $matrix_score $fwd_flag $widx_size -p 15 | sort -s -k1,1 -k2,2n | $bin_dir/mscan2bed -s $assembly -i $chrNC_dir | filterOverlaps -l$matrix_len | awk 'BEGIN { while((getline line < \"$pwmScore_tab\") > 0 ) {split(line,f,\" \"); pvalue[f[1]]=f[2]} close(\"$pwmScore_tab\")} {print \$1\"\t\"\$2\"\t\"\$3\"\t\"\$4\"\t\"\$5\"\t\"\$6\"\t\"\"$matrix_name\"\"\t\"\"P-value=\"pvalue[\$5]}' >$pwmout_bed" >&2
+    echo "..." >&2
+    python $bin_dir/matrix_scan_parallel.py -m $matrix_file -s "$(ls $assembly_dir/chrom*.seq|grep -v chromMt)" -c $matrix_score $fwd_flag $widx_size -p 15 | sort -s -k1,1 -k2,2n | $bin_dir/mscan2bed -s $assembly -i $chrNC_dir | filterOverlaps -l$matrix_len | awk -v scoretab="$pwmScore_tab" -v pwmname="$matrix_name" 'BEGIN { while((getline line < scoretab) > 0 ) {split(line,f," "); pvalue[f[1]]=f[2]} close(scoretab)} {print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"pwmname"\t""P-value="pvalue[$5]}' >$pwmout_bed
   fi
 fi
 
-echo "List of matches (BED format) : $pwmout_bed"
-nb_hits=`cat $pwmout_bed|wc -l`
-echo "Total number of PWM matches  : $nb_hits"
+if [ $w_flag == 1 ]
+then
+  echo "List of matches (BED format) : $pwmout_bed" >&2
+  nb_hits=`cat $pwmout_bed|wc -l`
+  echo "Total number of PWM matches  : $nb_hits" >&2
+fi
 
 rm $pwmScore_tab
