Changes to be committed: 	modified:   Makefile 	modified:   README 	new file:   examples/Encode_Helas3Stat1_peaks.bed 	modified:   examples/README.html 	modified:   examples/README.txt 	new file:   examples/results/seq_extract_stat1_peaks.fa 	modified:   filterOverlaps.c 	modified:   pwm_bowtie_wrapper 	modified:   pwm_mscan_wrapper 	modified:   pwm_scan 	modified:   pwmlib_scan 	new file:   seq_extract_bcomp.c

diff --git a/pwmlib_scan b/pwmlib_scan
--- a/pwmlib_scan
+++ b/pwmlib_scan
@@ -41,6 +41,8 @@
 #  case results are written to file. BED filenames include the matrix name, the cut-off, 
 #  and, should it be case, the forward scanning flag (fwd).
 #
+#  16.02.2018  Giovanna Ambrosini
+#              Add optional parameter to set the background base composition
 
 E_BADARGS=85   # Wrong number of arguments passed to the script.
 
@@ -57,25 +59,28 @@ pwm_format="logodds";
 p_value=""
 genome_root_dir=""
 assembly=""
+bg_freq=""
 
 display_usage() {
       echo "Usage:"
       echo    "    pwmlib_scan -l <pwmlib> -e <p-value> -d <genome-root-dir> -s <assembly[hg19|mm9|..]> [options]"
-      echo    "    - version 1.1.5"
+      echo    "    - version 1.1.6"
       echo    "    where options are:"
-      echo    "         -g  PWM format [def=logodds]. Accepted formats are : meme, logodds, and lpm"
-      echo    "         -f  Scan sequences in forward direction [def=bidirectional]"
-      echo    "         -o  Allow for overlapping matches [def=non-overlapping matches]"
-      echo    "         -w  Write output to file [def=STDOUT]"
-      echo -e "         -p  Distribute matrix_scan on multiple CPU-cores [def=non-parallel processing]"
-      echo -e "         -v  Verbose mode and keep PWM tmp files\n"
+      echo    "         -b <bg_comp>   Background model (residue priors), e.g. : 0.29,0.21,0.21,0.29"
+      echo    "                        [def=predefined for some common genome assemblies, else set to uniform]"
+      echo    "         -g             PWM format [def=logodds]. Accepted formats are : meme, logodds, and lpm"
+      echo    "         -f             Scan sequences in forward direction [def=bidirectional]"
+      echo    "         -o             Allow for overlapping matches [def=non-overlapping matches]"
+      echo    "         -w             Write output to file [def=STDOUT]"
+      echo -e "         -p             Distribute matrix_scan on multiple CPU-cores [def=non-parallel processing]"
+      echo -e "         -v             Verbose mode and keep PWM tmp files\n"
       echo -e "    Scan a genome assembly with a PWM collection. Accepeted PWM library formats are the MEME format"  
       echo -e "    (<meme>), and the MEME-like log-odds and letter-probability formats (<logodds> and <lpm>)."  
       echo -e "    Description of these formats is provided at http://ccg.vital-it.ch/pwmtools/pwmlib.html.\n"  
       echo    "Please report bugs to Giovanna.Ambrosini@epfl.ch"
 }
 # Parse options
-while getopts ":hfopwvl:e:g:d:s:" opt; do
+while getopts ":hfopwvb:l:e:g:d:s:" opt; do
   case ${opt} in
     h )
       display_usage
@@ -92,6 +97,9 @@ while getopts ":hfopwvl:e:g:d:s:" opt; do
       ;;
     p )
       parallel=1
+      ;;
+    b )
+      bg_freq=$OPTARG
       ;;
     g )
       pwm_format=$OPTARG
@@ -116,7 +124,7 @@ while getopts ":hfopwvl:e:g:d:s:" opt; do
       exit 1
       ;;
     \? )
-     echo "Invalid Option: -$OPTARG" 1>&2
+     echo "Invalid OPTION: -$OPTARG" 1>&2
      exit 1
      ;;
   esac
@@ -175,6 +183,12 @@ then
   exit 1
 fi
 
+bg_comp=""
+if [ -n "$bg_freq" ]
+then
+  bg_comp="-b $bg_freq"
+fi
+
 bin_dir=$(echo /home/local/bin)
 pwm_scan_cmd_flags=""
 
@@ -223,9 +237,9 @@ for f in *mat.tmp; do
       if [ $verbose == 1 ]; then
         echo "New PWM file: $f""2" >&2
         echo "Scanning the $assembly genome with $f""2" >&2
-        echo "Command: $bin_dir/pwm_scan -m $f""2 -e $p_value -d $genome_root_dir -s $assembly$pwm_scan_cmd_flags" >&2
+        echo "Command: $bin_dir/pwm_scan $bg_comp -m $f""2 -e $p_value -d $genome_root_dir -s $assembly$pwm_scan_cmd_flags" >&2
       fi
-      $bin_dir/pwm_scan -m $f"2" -e $p_value -d $genome_root_dir -s $assembly$pwm_scan_cmd_flags 
+      $bin_dir/pwm_scan $bg_comp -m $f"2" -e $p_value -d $genome_root_dir -s $assembly$pwm_scan_cmd_flags 
       if [ $verbose == 0 ]
       then
         rm $f"2"
@@ -234,9 +248,9 @@ for f in *mat.tmp; do
       if [ $verbose == 1 ]
       then
         echo "Scanning the $assembly genome with $f" >&2
-        echo "Command: $bin_dir/pwm_scan -m $f -e $p_value -d $genome_root_dir -s $assembly$pwm_scan_cmd_flags" >&2
+        echo "Command: $bin_dir/pwm_scan $bg_comp -m $f -e $p_value -d $genome_root_dir -s $assembly$pwm_scan_cmd_flags" >&2
       fi
-      $bin_dir/pwm_scan -m $f -e $p_value -d $genome_root_dir -s $assembly$pwm_scan_cmd_flags
+      $bin_dir/pwm_scan $bg_comp -m $f -e $p_value -d $genome_root_dir -s $assembly$pwm_scan_cmd_flags
   fi
   if [ $verbose == 0 ]
   then
